### ISSUE TITLE
Override the fontSize of Axis labels

### ISSUE THREAD

**Issue by xscotta** [d3plus/d3plus-axis#102]
I am using the Barchart function, and would like to override the default font-Size used for axis labels.
I presume it would be passed to the Axis module, so I am posting this request here.
The default fontSize for axis labels looks to be 10px.
I do not see a way to specify this using the conventions in the documentation.
For example:
  .xConfig({  labelConfig: {fontSize: 20} })
One clarification, I want to override the labels on each tick on the x and y axis, not the name/title of the axis.
Thanks in advance.

EDIT:
I can change the size of the text to 14px by using fontMin/fontMax
.xConfig({  shapeConfig: { labelConfig: {fontMin: 14,fontMax:14} } })

 ...but it merely increases the actual pixel size, it does not reformat based on that new size. The text wrapping and line-height stay based on the original default 10px, and so defeats the point of changing the size when the label is a multi word, multi line, piece of text.

**Comment by xscotta** [comment]
One clarification, I want to override the labels on each tick on the x and y axis, not the name/title of the axis.

**Comment by davelandry** [comment]
@xscotta you were close! your code should look like this:

```js
.xConfig({
  shapeConfig: {
    labelConfig: {
      fontSize: 20
    }
  }
})
```

The `fontMin` and `fontMax` properties are only used when `fontResize` is set to `true` (commonly used in Treemaps).
