### ISSUE TITLE
weird behaviour using jenks scale

### ISSUE THREAD

**Issue by cnavarreteliz** [d3plus/d3plus-axis#43]
Hi, I was trying to use `scale: jenks` and the last tick in ColorScale doesn't appear

JSFiddle: [https://jsfiddle.net/252k2gaa/2/](https://jsfiddle.net/252k2gaa/2/)

![image](https://user-images.githubusercontent.com/5233593/37975563-fd52eec2-31b5-11e8-912e-cfdd94737869.png)
![image](https://user-images.githubusercontent.com/5233593/37975578-0485ca48-31b6-11e8-9024-f89e0f8f2c34.png)

**Comment by nbond211** [comment]
Hey @cnavarreteliz ! Just a heads up - I recreated this issue in the [d3plus-legend](https://github.com/d3plus/d3plus-legend/issues/65) repo so I could refer to it there.
