### ISSUE TITLE
use locale when formatting time axes

### ISSUE THREAD

**Issue by cnavarreteliz** [d3plus/d3plus-axis#50]
![image](https://user-images.githubusercontent.com/5233593/38582396-ef6f9626-3ce5-11e8-9282-203ab109c395.png)

Hello, could be a good option set `locale` to use in axis. For example, now in Datachile we're using `es,en` languages, and dateFormat always is in english.

I was reading, and this one depend from [`d3-time-format`](https://github.com/d3/d3-time-format) that includes others languages like `ar`, `it`, `fr`, that can be applied in other projects with multilanguage.

**Comment by davelandry** [comment]
@cnavarreteliz totally. let's knock this out of the park and figure out a localization solution that works for all modules. We need to build in some plumbing to `d3plus-common` first ([here](https://github.com/d3plus/d3plus-common/issues/85) and [here](https://github.com/d3plus/d3plus-common/issues/86)), and then have `d3plus-plot` pass down the user's selected localization ([here](https://github.com/d3plus/d3plus-plot/issues/86)), then this one should be able to be hooked up!

**Comment by davelandry** [comment]
Example d3 usage: https://bl.ocks.org/mbostock/6f1cc065d4d172bcaf322e399aa8d62f
