### ISSUE TITLE
labels not rotating

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-axis#51]
### Expected Behavior
Expecting axis labels to rotate 90 degree when there's not enough room horizontally.

### Current Behavior
Some labels are hidden and labels appear horizontal

### Steps to Reproduce (for bugs)

1. https://jsfiddle.net/72zs3dm0/

### Your Environment

* Browser Name: Chrome 
* Operating System and Version: OS X 10.13.3

**Comment by davelandry** [comment]
@jspeis @nbond211 found the bug... we never released a new version of d3plus-axis 😮 

How's this look: https://jsfiddle.net/72zs3dm0/2/
