### ISSUE TITLE
use formatAbbreviate as the default tick formatter

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-axis#61]
### Expected Behavior
Scales that are not logarithmic and not time should use the new `formatAbbreviate` function from `d3plus-format`. The current logic is here: https://github.com/d3plus/d3plus-axis/blob/master/src/Axis.js#L298-L308

### Current Behavior
Currently, numbers return as is.

**Comment by cnavarreteliz** [comment]
@davelandry  I prefer rewrite my logic, because in this PR I'm spoiling the source code of `d3plus-axis` with my `linter`.

**Comment by davelandry** [comment]
@cnavarreteliz ok, delete the other branch, close that old PR, and resubmit a new PR
