### ISSUE TITLE
remove month labels in timeScale

### ISSUE THREAD

**Issue by cnavarreteliz** [d3plus/d3plus-axis#64]
### Expected Behavior
In `d3plus-timeline`, scale shows month labels between years.

### Current Behavior
Time scale shows months when there are so much width between year labels.

### Steps to Reproduce (for bugs)
```
 new d3plus.Timeline()
      .domain([2001, 2004])
      .buttonBehavior("ticks")
      .ticks([2001, 2002, 2003, 2004])
      .width(800)
      .render();
```

### Your Environment

* Browser Name: Google Chrome
* Operating System and Version: Macbook Pro High Sierra

**Comment by davelandry** [comment]
closing in favor of https://github.com/d3plus/d3plus-timeline/issues/19
