### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by pachamaltese** [d3plus/d3plus-axis#80]
as in e4f1bfd `npm` install returns `npm ERR! 404 Not Found: event-stream@3.3.6`

**Comment by davelandry** [comment]
@pachamaltese I just pushed some an update that includes some recent minor d3plus dependency upgrades. Can you try again and see if you still get this error?

**Comment by pachamaltese** [comment]
@davelandry I just pulled and did `rm -rf node_modules && rm package-lock.json && npm install && npm run build` and it works ok. Check this:

```
    d3plus-axis v0.3.53
    build compile


[ done ] transpiling ES6 for modules
[ done ] bundling build/d3plus-axis.js
[ done ] bundling build/d3plus-axis.full.js
[ done ] uglifying builds
[ done ] creating .zip distribution
```
