### ISSUE TITLE
Ticks overlapping

### ISSUE THREAD

**Issue by gargulamen** [d3plus/d3plus-axis#9]
If i set specific ticks, the automatic ones still generate if I have a Width set.
But without width set the axis is too small and the ticks overlap.

**Comment by davelandry** [comment]
Hmm, interesting. I'll take a look into this. Can you please post a snippit of your code?

**Comment by gargulamen** [comment]
console.log(brushDomain); //Array [ 2011, 2012, 2013, 2014, 2015, 2016 ]
    console.log(selectedDate); //2011
    var width = window.innerWidth;

    var timebrush = new d3plus.Timeline()
        .width(width)
        .select('#chartTimeline')
        .domain([brushDomain[0], brushDomain[brushDomain.length - 1]])
        .ticks(brushDomain)
        .selection(selectedDate)
        .render();

![timebrushd3](https://cloud.githubusercontent.com/assets/20678750/20268805/99f5c612-aa78-11e6-9ba4-36507f2aae31.PNG)

Without .width()

![timebrushd3nowidth](https://cloud.githubusercontent.com/assets/20678750/20268929/faece75c-aa78-11e6-9a77-cc63ed7315aa.PNG)

And the overlapping part

console.log(brushDomain) //Array [ "2015-01-31", "2015-02-28", "2015-03-31", "2015-04-30", "2015-05-31", "2015-06-30", "2015-07-31", "2015-08-31", "2015-09-30", "2015-10-31", … ]

timebrush.domain([brushDomain[0], brushDomain[brushDomain.length-1]])
    .ticks(brushDomain)
    .tickFormat(function(d) {
         date = new Date(d);
         date.setDate(date.getDate()-1);
         return meses[date.getMonth()] + ' ' + date.getFullYear();
     });
 
![timebrushd3overlap](https://cloud.githubusercontent.com/assets/20678750/20269184/12926930-aa7a-11e6-913d-10ddc02c965b.PNG)
